---
version: "3.9"
services:
  web:
    image: main/backend
    build:
      context: .
      dockerfile: ./docker-images/python3.10.8-slim.dockerfile
    ports:
      - "80:80"
    volumes:
      - './data:/data'
