[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Ian Cleary", email = "hello@iancleary.me"},
]
dependencies = [
    "fastapi>=0.85.1",
    "uvicorn>=0.18.3",
    "SQLAlchemy>=1.4.41",
]
requires-python = ">=3.9"
license = {text = "MIT"}

[tool.pdm]

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"
