[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Ian Cleary", email = "hello@iancleary.me"},
]
dependencies = [
    "fastapi==0.88.0",
    "SQLAlchemy==1.4.44",
    "uvicorn[standard]==0.20.0",
    "gunicorn==20.1.0",
    "fastapi-restful[session]>=0.4.3",
]
requires-python = ">=3.9"
license = {text = "MIT"}
[project.optional-dependencies]

[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "pytest==7.2.0",
    "black==22.10.0",
    "isort==5.10.1",
    "mypy==0.990",
    "autoflake==2.0.0",
    "httpx>=0.23.1",
]

[tool.isort]
src_paths = ["app", "test"]
force_single_line = true
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true
line_length = 88

[tool.autoflake]
remove-all-unused-imports = true
recursive = true
remove-unused-variables = true
in-place = true
expand-star-imports = true
exclude = "__init__.py"
remove-duplicate-keys = true

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"
