[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Ian Cleary", email = "hello@iancleary.me"},
]
dependencies = [
    "fastapi>=0.85.1",
    "SQLAlchemy>=1.4.41",
    "uvicorn[standard]>=0.19.0",
    "gunicorn>=20.1.0",
]
requires-python = ">=3.9"
license = {text = "MIT"}
[project.optional-dependencies]

[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "pytest>=7.2.0",
    "black>=22.10.0",
    "isort>=5.10.1",
    "mypy>=0.990",
    "autoflake>=1.7.7",
    "pre-commit>=2.20.0",
]

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"
