name: Deploy

on:
  push:
    branches:
      - main

jobs:
  BuildPush:
    strategy:
      matrix:
        image:
          - name: latest
            python_version: "3.10.8"
          - name: python3.10.8
            python_version: "3.10.8"
          - name: python3.10.8-slim
            python_version: "3.10.8-slim"
      fail-fast: true
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up PDM (for create_production_requirements)
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.10.8"
      - name: Deploy Image
        run: bash scripts/build-push.sh
        env:
          NAME: ${{ matrix.image.name }}
          PYTHON_VERSION: ${{ matrix.image.python_version }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
