name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  Linting:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.10']
        os: [ubuntu-22.04]

    steps:
      - uses: actions/checkout@v3
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Disable venv
        run: |
          pdm config python.use_venv false
      - name: Install dependencies
        run: |
          pdm sync -d -G dev
      - name: Run scripts/lint (with pdm)
        run: |
          pdm run -v scripts/lint.sh