name: Test

on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  Testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10']
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v2
        with:
          python-version: ${{ matrix.python-version }}
      - namme: Disable venv
        run: |
          pdm config python.use_venv false
      - name: Install dependencies
        run: |
          pdm sync -d -G test
      - name: Run Tests
        run: |
          export DATABASE=data/test.db && pdm run -v pytest tests